name: Rcc
on:
  workflow_dispatch:
    # enables manual triggering
  push:
    branches:
      - master
      - maintenance
      - series10
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20.x"
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
      - name: Install invoke
        run: python -m pip install invoke
      - name: What
        run: inv what
      - name: Building
        run: inv build

  robot:
    name: Robot
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "windows"]
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: "1.20.x"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - uses: actions/checkout@v4
      - name: Install invoke
        run: python -m pip install invoke
      - name: Setup
        run: inv robotsetup
      - name: What
        run: inv what
      - name: Testing
        run: inv robot
      - uses: actions/upload-artifact@v4
        if: success() || failure()
        with:
          name: ${{ matrix.os }}-test-reports
          path: ./tmp/output/

  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    needs:
      - build
      - robot
    if: success() && github.ref == 'refs/heads/master'
    steps:
      - name: Pipeline
        run: |
          curl -X POST https://api.github.com/repos/robocorp/rcc-pipeline/dispatches \
          -H 'Accept: application/vnd.github.v3+json' \
          -u ${{ secrets.TRIGGER_TOKEN }} \
          --data '{"event_type": "pipes"}'
