name: Rcc
on:
    workflow_dispatch:
        # enables manual triggering
    push:
        branches:
            - master
            - maintenance
            - series10

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-go@v2
              with:
                  go-version: '1.18.x'
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'
            - uses: actions/checkout@v1
            - name: What
              run: rake what
            - name: Building
              run: rake clean build

    robot:
        name: Robot
        runs-on: ${{ matrix.os }}-latest
        strategy:
            fail-fast: false
            matrix:
                os: ['ubuntu']
        steps:
            - uses: actions/setup-go@v2
              with:
                  go-version: '1.18.x'
            - uses: ruby/setup-ruby@v1
              with:
                  ruby-version: '2.7'
            - uses: actions/setup-python@v1
              with:
                  python-version: '3.7'
            - uses: actions/checkout@v1
            - name: Setup
              run: rake robotsetup
            - name: What
              run: rake what
            - name: Testing
              run: rake clean robot
            - uses: actions/upload-artifact@v1
              if: success() || failure()
              with:
                  name: ${{ matrix.os }}-test-reports
                  path: ./tmp/output/
    trigger:
        name: Trigger
        runs-on: ubuntu-latest
        needs:
            - build
            - robot
        steps:
            - name: Pipeline
              run: |
                  curl -X POST https://api.github.com/repos/robocorp/rcc-pipeline/dispatches \
                  -H 'Accept: application/vnd.github.v3+json' \
                  -u ${{ secrets.TRIGGER_TOKEN }} \
                  --data '{"event_type": "pipes"}'
